"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthProvider = exports.ConsultationType = exports.AppointmentStatus = exports.Role = void 0;
var role_enum_1 = require("./enums/role.enum");
Object.defineProperty(exports, "Role", { enumerable: true, get: function () { return role_enum_1.Role; } });
var appointment_status_enum_1 = require("./enums/appointment-status.enum");
Object.defineProperty(exports, "AppointmentStatus", { enumerable: true, get: function () { return appointment_status_enum_1.AppointmentStatus; } });
var consultation_type_enum_1 = require("./enums/consultation-type.enum");
Object.defineProperty(exports, "ConsultationType", { enumerable: true, get: function () { return consultation_type_enum_1.ConsultationType; } });
var auth_provider_enum_1 = require("./enums/auth-provider.enum");
Object.defineProperty(exports, "AuthProvider", { enumerable: true, get: function () { return auth_provider_enum_1.AuthProvider; } });
