export enum CaseCategory {
  CRIMINAL = 'CRIMINAL',
  FAMILY = 'FAMILY',
  LAND_PROPERTY = 'LAND_PROPERTY',
  COMMERCIAL = 'COMMERCIAL',
  CIVIL = 'CIVIL',
  LABOR = 'LABOR',
  CONSTITUTIONAL = 'CONSTITUTIONAL',
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',
  IMMIGRATION = 'IMMIGRATION',
  TAX = 'TAX',
  CONSUMER_RIGHTS = 'CONSUMER_RIGHTS',
  OTHER = 'OTHER',
}
