export enum CaseStage {
  INTAKE = 'INTAKE',
  LAWYER_ASSIGNED = 'LAWYER_ASSIGNED',
  DISCOVERY = 'DISCOVERY',
  PRE_FILING = 'PRE_FILING',
  FILED = 'FILED',
  HEARING_SCHEDULED = 'HEARING_SCHEDULED',
  IN_TRIAL = 'IN_TRIAL',
  JUDGMENT = 'JUDGMENT',
  APPEAL = 'APPEAL',
  SETTLEMENT = 'SETTLEMENT',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
}
