export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  LAWYER_APPROVED = 'LAWYER_APPROVED',
  LAWYER_REJECTED = 'LAWYER_REJECTED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}
